web:
   build: .
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "80:80"
   links:
     - db
   volumes:
     - ./conf:/var/www/html/conf
     - ./uploads:/var/www/html/uploads
   restart: always

db:
  image: mysql:5.7
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: vanillauser
    MYSQL_PASSWORD: vanilla
    MYSQL_DATABASE: vanilla
  ports:
    - "3306:3306"